# Machine learning linearRegression- Dwelling and industries

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

In [5]:
data = pd.read_csv('machinedata.csv')

In [6]:
data.head(3)

,census_year,clue_small_area,accommodation_and_food_services,administrative_and_support_services,agriculture_forestry_and_fishing,arts_and_recreation_services,construction,education_and_training,electricity_gas_water_and_waste_services,financial_and_insurance_services,...,mining,other_services,professional_scientific_and_technical_services,public_administration_and_safety,rental_hiring_and_real_estate_services,retail_trade,transport_postal_and_warehousing,wholesale_trade,total_establishments_in_block,Total_Dwel
0,2002,Carlton,190,40,0,31,13,61,13,41,...,0,146,143,13,15,166,10,24,1069,80.0
1,2002,Docklands,23,6,1,9,4,1,6,1,...,0,14,7,7,4,11,36,3,147,850.0
2,2002,East Melbourne,54,22,0,42,4,12,8,17,...,0,40,70,14,5,16,6,7,488,78.0

In [9]:
# Encoding 'clue_small_area'
le = preprocessing.LabelEncoder()
data['clue_small_area'] = le.fit_transform(data['clue_small_area'].values)

In [17]:
data.head(3)

,census_year,clue_small_area,accommodation_and_food_services,administrative_and_support_services,agriculture_forestry_and_fishing,arts_and_recreation_services,construction,education_and_training,electricity_gas_water_and_waste_services,financial_and_insurance_services,...,mining,other_services,professional_scientific_and_technical_services,public_administration_and_safety,rental_hiring_and_real_estate_services,retail_trade,transport_postal_and_warehousing,wholesale_trade,total_establishments_in_block,Total_Dwel
0,2002,0,190,40,0,31,13,61,13,41,...,0,146,143,13,15,166,10,24,1069,80.0
1,2002,1,23,6,1,9,4,1,6,1,...,0,14,7,7,4,11,36,3,147,850.0
2,2002,2,54,22,0,42,4,12,8,17,...,0,40,70,14,5,16,6,7,488,78.0

In [18]:
data.describe()

,census_year,clue_small_area,accommodation_and_food_services,administrative_and_support_services,agriculture_forestry_and_fishing,arts_and_recreation_services,construction,education_and_training,electricity_gas_water_and_waste_services,financial_and_insurance_services,...,mining,other_services,professional_scientific_and_technical_services,public_administration_and_safety,rental_hiring_and_real_estate_services,retail_trade,transport_postal_and_warehousing,wholesale_trade,total_establishments_in_block,Total_Dwel
count,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,...,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000
mean,2012.000000,6.000000,195.161172,51.721612,1.252747,42.879121,21.340659,39.586081,14.410256,69.586081,...,3.776557,109.358974,198.714286,21.593407,28.853480,174.054945,26.069597,41.893773,1185.611722,502.512821
std,6.066422,3.748529,412.858066,127.443425,1.878243,40.510756,28.234400,77.957290,15.601901,190.121287,...,11.170367,221.723984,466.975774,45.759356,56.544755,401.996407,30.244328,55.610380,2325.187452,1107.539071
min,2002.000000,0.000000,1.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,15.000000,0.000000
25%,2007.000000,3.000000,24.000000,5.000000,0.000000,16.000000,4.000000,7.000000,6.000000,4.000000,...,0.000000,17.000000,20.000000,4.000000,4.000000,16.000000,5.000000,6.000000,328.000000,0.000000
50%,2012.000000,6.000000,58.000000,16.000000,1.000000,37.000000,12.000000,13.000000,9.000000,15.000000,...,0.000000,40.000000,74.000000,7.000000,11.000000,29.000000,15.000000,22.000000,480.000000,78.000000
75%,2017.000000,9.000000,148.000000,28.000000,2.000000,50.000000,24.000000,24.000000,15.000000,30.000000,...,1.000000,74.000000,127.000000,15.000000,23.000000,118.000000,36.000000,53.000000,903.000000,532.000000
max,2022.000000,12.000000,2491.000000,702.000000,10.000000,264.000000,157.000000,470.000000,88.000000,1114.000000,...,66.000000,1490.000000,2911.000000,230.000000,347.000000,2278.000000,133.000000,244.000000,14161.000000,8046.000000

In [20]:
# All the values are going to be scaled except for target value
scaler = StandardScaler()
data.iloc[:,2:-2] = scaler.fit_transform(data.iloc[:,2:-2])

/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

In [21]:
data.describe()

,census_year,clue_small_area,accommodation_and_food_services,administrative_and_support_services,agriculture_forestry_and_fishing,arts_and_recreation_services,construction,education_and_training,electricity_gas_water_and_waste_services,financial_and_insurance_services,...,mining,other_services,professional_scientific_and_technical_services,public_administration_and_safety,rental_hiring_and_real_estate_services,retail_trade,transport_postal_and_warehousing,wholesale_trade,total_establishments_in_block,Total_Dwel
count,273.000000,273.000000,2.730000e+02,2.730000e+02,2.730000e+02,2.730000e+02,2.730000e+02,2.730000e+02,2.730000e+02,2.730000e+02,...,2.730000e+02,2.730000e+02,2.730000e+02,2.730000e+02,2.730000e+02,2.730000e+02,2.730000e+02,2.730000e+02,273.000000,273.000000
mean,2012.000000,6.000000,-3.253401e-17,-1.626700e-17,-1.626700e-17,6.506802e-17,2.602721e-17,1.301360e-17,-4.880101e-18,2.765391e-17,...,6.506802e-18,-2.928061e-17,-3.090731e-17,-4.717431e-17,-6.506802e-18,-8.133502e-18,3.904081e-17,3.904081e-17,1185.611722,502.512821
std,6.066422,3.748529,1.001837e+00,1.001837e+00,1.001837e+00,1.001837e+00,1.001837e+00,1.001837e+00,1.001837e+00,1.001837e+00,...,1.001837e+00,1.001837e+00,1.001837e+00,1.001837e+00,1.001837e+00,1.001837e+00,1.001837e+00,1.001837e+00,2325.187452,1107.539071
min,2002.000000,0.000000,-4.711492e-01,-4.065851e-01,-6.682033e-01,-1.010946e+00,-7.572271e-01,-5.087245e-01,-9.253181e-01,-3.666811e-01,...,-3.387080e-01,-4.896087e-01,-4.263160e-01,-4.727572e-01,-5.112140e-01,-4.337716e-01,-8.635495e-01,-7.547280e-01,15.000000,0.000000
25%,2007.000000,3.000000,-4.153377e-01,-3.672800e-01,-6.682033e-01,-6.647243e-01,-6.152958e-01,-4.187668e-01,-5.400433e-01,-3.456032e-01,...,-3.387080e-01,-4.173143e-01,-3.834085e-01,-3.851828e-01,-4.403437e-01,-3.938971e-01,-6.979256e-01,-6.466364e-01,328.000000,0.000000
50%,2012.000000,6.000000,-3.328337e-01,-2.808087e-01,-1.348129e-01,-1.453915e-01,-3.314331e-01,-3.416603e-01,-3.474059e-01,-2.876392e-01,...,-3.387080e-01,-3.133912e-01,-2.675585e-01,-3.195021e-01,-3.163206e-01,-3.614991e-01,-3.666779e-01,-3.583919e-01,480.000000,78.000000
75%,2017.000000,9.000000,-1.144407e-01,-1.864763e-01,3.985774e-01,1.761003e-01,9.436095e-02,-2.002982e-01,3.786889e-02,-2.085973e-01,...,-2.490210e-01,-1.597658e-01,-1.538538e-01,-1.443533e-01,-1.037095e-01,-1.396975e-01,3.289424e-01,2.000818e-01,903.000000,532.000000
max,2022.000000,12.000000,5.571056e+00,5.111858e+00,4.665700e+00,5.468350e+00,4.813578e+00,5.531290e+00,4.725379e+00,5.503498e+00,...,5.580633e+00,6.238282e+00,5.818861e+00,4.562768e+00,5.636788e+00,5.243353e+00,3.542045e+00,3.641000e+00,14161.000000,8046.000000

In [22]:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:,:-2], data.iloc[:,-1], test_size=0.33, random_state=42)

In [25]:
# creating model
model = LinearRegression()
model.fit(X_train, y_train)

/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

LinearRegression()

In [26]:
y_pred = model.predict(X_test)

/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

In [27]:
score = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {score}")

Mean Squared Error: 967117.4102596253

/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

In [31]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/adrienauguste/opt/anaconda3/envs/MachineLearning/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets